export const consoleList = [
    "Mobile",
    "Nintendo Switch",
    "Nintendo Switch 2",
    "Nintendo DS",
    "Nintendo 3DS",
    "PC",
    "Playstation 3",
    "Playstation 4",
    "Playstation 5",
    "Steam Deck",
    "Steam machine",
    "Xbox 360",
    "Xbox One",
    "Xbox Series X",
    "Xbox Series S",
    "Others | Autres",
  ];