import type Game from "@/models/Game";

export const GamesMockList: Game[] = [
  {
    id: 1,
    title: "The outer wolrd 2",
    hourPlay: 20,
    isFavor: false,
    rating: 4,
    note: "",
    completionDate: "",
    type: "game",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "Xbox game pass",
  },
  {
    id: 2,
    title: "Digimon Time stranger",
    hourPlay: 30,
    isFavor: false,
    rating: null,
    note: "",
    completionDate: "",
    type: "game",
    console: "pc",
    year: 2025,
    platformBuy: "steam",
  },
  {
    id: 3,
    title: "Arc Raiders",
    hourPlay: null,
    isFavor: false,
    rating: null,
    note: "",
    completionDate: "",
    type: "game",
    console: "pc",
    year: 2025,
    platformBuy: "steam",
  },
  {
    id: 4,
    title: "Battlefiled 6",
    hourPlay: null,
    isFavor: false,
    rating: 3,
    note: "Campagne fini (6h)",
    completionDate: "2025-10-20",
    type: "game",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "xbox store",
  },
    {
    id: 4,
    title: "Star Wars Outlaws: A Pirate’s Fortune",
    hourPlay: 5,
    isFavor: false,
    rating: 1,
    note: "",
    completionDate: "2025-10-20",
    type: "dlc",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "Ubisoft+",
  },
];
