import type Game from "@/models/Game";

export const GamesMockList: Game[] = [
  {
    id: 1,
    title: "The outer world 2",
    hourPlay: 20,
    isFavor: false,
    note: "",
    finish: false,
    type: "game",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "Xbox game pass",
  },
  {
    id: 2,
    title: "Arc Raiders",
    hourPlay: null,
    isFavor: false,
    note: "fais en solo",
    finish: false,
    type: "game",
    console: "pc",
    year: 2025,
    platformBuy: "steam",
  },
  {
    id: 3,
    title: "Battlefiled 6",
    hourPlay: null,
    isFavor: false,
    note: "Campagne fini (6h)",
    finish: true,
    type: "game",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "xbox store",
  },
    {
    id: 4,
    title: "Star Wars Outlaws: A Pirate’s Fortune",
    hourPlay: 5,
    isFavor: false,
    note: "",
    finish: true,
    type: "dlc",
    console: "xbox serie x",
    year: 2025,
    platformBuy: "Ubisoft+",
  },
];
